version: '3.5'

services:
  sql-server:
    container_name: sql-server
    cap_add: [ 'SYS_PTRACE' ]
    # image: mcr.microsoft.com/azure-sql-edge:latest # Apple Silicon
    image: mcr.microsoft.com/mssql/server:latest # Windows
    restart: always
    environment:
      ACCEPT_EULA: ${ACCEPT_EULA:-1}
      MSSQL_USER: ${MSSQL_USER:-SA}
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD:-Password1!}
    ports:
      - 1433:1433
    volumes:
      - sql-server:/var/opt/mssql

volumes:
  sql-server:
